export const ActionTypes ={
    SET_PRODUCTS : 'SET_PRODUCTS',
    ADD_PRODUCT : 'ADD_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    IS_ADMIN_LOGGED: 'IS_ADMIN_LOGGED'
}